# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/spik',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/spik',
                'lib_path': 'spik'},
  'syms': {'spik.core': {'spik.core.foo': ('core.html#foo', 'spik/core.py')}}}
